config_name: bimanual_yam
selectable: false
policy_contract: bimanual_yam
asset_builds: [yam]

workspace:
  anchor: Table
  robot_root_offsets:
    robot0: [-0.24, -0.40, 0.025]
    robot1: [0.24, -0.40, 0.025]

config:
  sim: real_time_30hz
  robot: dual_yam
  camera: bimanual_yam

observation:
  collect_freq: 30
  robot: {joint_states: true, world_ee_state: true}
  vision:
    approximate_depth: false
    depth: false
    intrinsic_matrix: false
    extrinsic_matrix: false
    shape: true
