config_name: bimanual_yam_molmoact2
layout_config_name: bimanual_yam_molmoact2

config:
  sim: real_time_30hz
  scene: default
  robot: dual_yam
  camera: bimanual_yam

observation:
  collect_freq: 30
  robot: {joint_states: true, world_ee_state: true}
  vision:
    approximate_depth: false
    depth: false
    intrinsic_matrix: false
    extrinsic_matrix: false
    shape: true
