config_name: bimanual_yam
layout_config_name: arx_x5

diagnostics:
  matched_replay_manifest: reference/bimanual_yam_matched_frames.yml

config:
  sim: real_time_30hz
  scene: molmo_yam
  robot: dual_yam
  camera: bimanual_yam

observation:
  collect_freq: 30
  robot: {joint_states: true, world_ee_state: true}
  vision:
    approximate_depth: false
    depth: false
    intrinsic_matrix: false
    extrinsic_matrix: false
    shape: true
