config_name: openarm_anvil_v2
hardware_calibration: openarm_anvil_v2

config:
  sim: openarm_anvil_v2
  robot: dual_openarm_anvil_v2
  camera: openarm_anvil_v2

observation:
  collect_freq: 30
  robot: {joint_states: true, world_ee_state: true}
  vision:
    approximate_depth: false
    depth: false
    intrinsic_matrix: false
    extrinsic_matrix: false
    shape: true
