config_name: moonlake_office
component: moonlake_office
layout_set: moonlake_office
layout_source: bundled
asset_builds: [moonlake_office]
task_asset_builds:
  pack_item_into_container: [moonlake_packing]
compatible_environments: [bimanual_yam_moonlake_office]
