sources:
  openarm_isaac_lab:
    repository: https://github.com/enactic/openarm_isaac_lab.git
    revision: bad82e23716e6941c2de78ccb978f57c78b37734
  hardware_modifications:
    repository: https://huggingface.co/datasets/lerobot/openarms-hardware-modifications
    revision: ffe34b93c070343042eb9412fbfeffce16139947
    sha256:
      J3-J4_Cover front extended.stl: b2bb0cf3c0d5fa95bcf1fb684e6e810fe4cb8c25310434fa8c41e122d43884c1
      J3-J4_Cover back extended.stl: a3b8fd1dcb0e72abdc4d7b6a3667162a798fbd7c4f954eaab63d9c99a44efb23
      jaw_normal.stl: 6ae41c9fbba411333954b8f4d1c6867b61fad1be7d7b936899c27d43410a2137
      head camera holder v4.stl: 959ae5e0ad6e0870465e361df30db3d1bbdeebb9ba8001274c3ce9e1712f03d3
      arducam_holder.stl: 1d31e0ac9ac2b118fb0925dc45bb3736dff087a9e6c2f9c27e64b24ee488074c
      arducam_holder.step: b51c4d565afe4a632c61af15b42a9319c9361271c98840ccd9c670a893b7291d

asset:
  output: openarm_bimanual.usd
  upper_arm_extension_m: 0.05
  jaw_mesh: jaw_normal.stl

robot_config:
  urdf_path: openarm.urdf
  base_link: openarm_body_link
  left:
    camera_mount_links:
      left_wrist_camera_holder: openarm_left_link7
    ee_joints: openarm_left_joint7
    ee_link: openarm_left_link7
    arm_joints_name:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    gripper_joints_name: [openarm_left_finger_joint1, openarm_left_finger_joint2]
    gripper_move:
      base: openarm_left_finger_joint1
      sign: 1.0
      mimic: [openarm_left_finger_joint2, 1.0, 0.0]
    gripper_scale: [0.0, 0.044]
    physical_gripper_interface: true
  right:
    camera_mount_links:
      right_wrist_camera_holder: openarm_right_link7
    ee_joints: openarm_right_joint7
    ee_link: openarm_right_link7
    arm_joints_name:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    gripper_joints_name: [openarm_right_finger_joint1, openarm_right_finger_joint2]
    gripper_move:
      base: openarm_right_finger_joint1
      sign: 1.0
      mimic: [openarm_right_finger_joint2, 1.0, 0.0]
    gripper_scale: [0.0, 0.044]
    physical_gripper_interface: true
