common:
  data_source: "datagen"
  render_interval: 10
  robot_self_collision: true

tasks:
  match_and_pick_from_conveyor:
    data_source: "teleop"

  classify_objects:
    data_source: "teleop"

  fill_egg_holder:
    data_source: "teleop"
    render_interval: 5
    robot_self_collision: false

  fill_pen_holder:
    data_source: "teleop"

  put_bottles_into_dustbin:
    data_source: "teleop"

  hang_mugs:
    data_source: "teleop"

  hang_mugs_random:
    data_source: "teleop"

  fold_clothes:

  fold_clothes_random:

  arrange_largest_number:

  arrange_largest_number_random:

  sort_nesting_dolls_by_size:

  sort_nesting_dolls_by_size_random:

  stack_blocks:

  stack_blocks_random:

  make_toast:
    data_source: "teleop"
    robot_self_collision: false

  make_toast_random:
    data_source: "teleop"
    robot_self_collision: false

  organize_table:
    data_source: "teleop"

  pack_objects_into_box:
    data_source: "teleop"

  pack_objects_into_box_random:
    data_source: "teleop"

  pack_item_into_container:
    data_source: "teleop"

  pour_balls_into_vase:
    data_source: "teleop"

  pour_liquid_into_cup:
    data_source: "teleop"

  pour_liquid_into_cup_random:
    data_source: "teleop"

  press_by_number:
    robot_self_collision: false

  push_T:
    data_source: "teleop"

  push_T_random:
    data_source: "teleop"

  stack_bowls:
    data_source: "teleop"

  stack_bowls_random:
    data_source: "teleop"

  store_laptop_and_headphones:
    data_source: "teleop"
    render_interval: 5
    robot_self_collision: false

  store_laptop_and_headphones_random:
    data_source: "teleop"
    render_interval: 5
    robot_self_collision: false

  swap_blocks:
    robot_self_collision: false

  sweep_blocks:
    data_source: "teleop"

  sweep_blocks_random:
    data_source: "teleop"
