Rigid:
  - common:
      xlim: [-0.15, -0.09]
      ylim: [-0.06, -0.02]
      rotate_deg: 10
      rotate_rand: false
      relative_plane: Table
    category:
      - name: piper_blue_cube
        index: [0]
    select_mode:
      nums: 1
      mode: unique
      label: [cube]

Articulation:
  - common:
      xlim: [0.09, 0.11]
      ylim: [0.12, 0.14]
      rotate_deg: 0
      rotate_rand: false
      relative_plane: Table
    category:
      - name: piper_red_bin
        index: [0]
    select_mode:
      nums: 1
      mode: unique
      label: [bin]
