config_name: openarm_wowrobo_v1_1
layout_config_name: arx_x5
hardware_calibration: openarm_wowrobo_v1_1

config:
  sim: openarm_wowrobo_v1_1
  scene: default
  robot: dual_openarm_wowrobo_v1_1
  camera: openarm_wowrobo_v1_1

observation:
  collect_freq: 30
  robot: {joint_states: true, world_ee_state: true}
  vision:
    approximate_depth: false
    depth: false
    intrinsic_matrix: false
    extrinsic_matrix: false
    shape: true
