calibration_required: openarm_wowrobo_v1_1
decimation: 1
dt: 0.004166666666666667
render_interval: 8
frequency_settings:
  /app/runLoops/main/rateLimitFrequency: 150
scene: {num_envs: 1, env_spacing: 7}
